# see https://docs.codecov.io/docs/codecov-yaml
# Validation check:
# $ curl --data-binary @.codecov.yml https://codecov.io/validate


# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    # after_n_builds: 2
    wait_for_ci: yes

coverage:
  precision: 0  # 2 = xx.xx%, 0 = xx%
  round: nearest # how coverage is rounded: down/up/nearest
  range: 40...100 # custom range of coverage colors from red -> yellow -> green
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: true
    patch: off
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

comment:
  layout: header, diff
  require_changes: true
  behavior: default  # update if exists else create new
  # branches: *
